Chess/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('administrador.urls')),
    path('captcha/', include('captcha.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

administrador/urls.py
from django.urls import path, include
from . import views
from .views import *
from usuario.models import Usuario
from django.conf.urls import url
# from django.contrib.auth.views import LogoutView
# from django.conf import settings

app_name  = 'administrador'

urlpatterns =[
    #///////////////////////////////////////////////////////////////////////
    path('', views.presentacion , name='presentacion'),
    #///////////////////////////////////////////////////////////////////////
    path('nosotros/', views.nosotros , name='nosotros'),
    #///////////////////////////////////////////////////////////////////////
    path('registro/', views.registro,  name='registro'),
    #///////////////////////////////////////////////////////////////////////
    path('tienda_chess/', views.tienda_chess , name='tienda_chess'), #CAMBIAR
    #///////////////////////////////////////////////////////////////////////
    path('configuraciones/', views.configuraciones, name='configuraciones'),
    #///////////////////////////////////////////////////////////////////////
    path('crear_usuario/', views.CrearUsuario.as_view(), name='CrearUsuario'),
    #///////////////////////////////////////////////////////////////////////
    path('logout_cuenta/', views.logout_cuenta, name='logout_cuenta'),
    #///////////////////////////////////////////////////////////////////////
    path('publicaciones/', views.publicaciones, name='publicaciones'),
    #///////////////////////////////////////////////////////////////////////
    path('0006/<int:pk>', views.Editar_usuario.as_view(), name="Editar_usuario"),
    #///////////////////////////////////////////////////////////////////////
    path('llenar_info/', views.llenar_info, name='llenar_info'),
    #///////////////////////////////////////////////////////////////////////
    path('registro_formularios/', views.registro_formularios, name='registro_formularios'),
    #///////////////////////////////////////////////////////////////////////
    path('Tienda/', views.Tienda, name='Tienda'),
    #///////////////////////////////////////////////////////////////////////
    path('perfil_usuario/', views.perfil_usuario, name='perfil_usuario'),
    #///////////////////////////////////////////////////////////////////////

    #///////////////////////////////////////////////////////////////////////
    path('Ver_publicacion/<int:pk>', views.Ver_publicaciones.as_view(), name="Ver_publicaciones"),
    path('Ver_publicaciones_Comunidad/<int:pk>', views.Ver_publicaciones_Comunidad.as_view(), name="Ver_publicaciones_Comunidad"),
    path('Editar_publicacion<int:pk>', views.Editar_publicaciones.as_view(), name="Editar_publicaciones"),
    path('Eliminar_publicacion<int:pk>', views.Eliminar_publicaciones.as_view(), name="Eliminar_publicaciones"),
    #///////////////////////////////////////////////////////////////////////


]

usuario/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Usuario(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    #///////////////////////////////////////////////////////////////////////
    nombre_usr = models.CharField(max_length=20,default='Nombre')
    #///////////////////////////////////////////////////////////////////////
    primer_apellido = models.CharField(max_length=30,default='Apellidos')
    #///////////////////////////////////////////////////////////////////////
    fecha_nacimiento = models.DateField(blank=True)
    #///////////////////////////////////////////////////////////////////////
    lugar_procedencia = models.CharField(max_length=50,default='Lugar de procedencia')
    #///////////////////////////////////////////////////////////////////////
    correo_usr = models.EmailField(max_length=254, default='Correo@ejemplo.com')
    #///////////////////////////////////////////////////////////////////////
    foto_perfil = models.ImageField(blank=True, upload_to='media')

    def __str__(self):
        return '{}'.format(self.user)

class FichaUsuario(models.Model):
        user = models.OneToOneField(User, on_delete=models.CASCADE)
        #///////////////////////////////////////////////////////////////////////
        titulo_usr = models.CharField(max_length=50)
        #///////////////////////////////////////////////////////////////////////
        nivel_elo = models.IntegerField()
        def __str__(self):
            return '{}'.format(self.user)

class Publicaciones(models.Model):
        user = models.ForeignKey(User, on_delete=models.CASCADE)
        #///////////////////////////////////////////////////////////////////////
        titulo_publ = models.CharField(max_length=50)
        #///////////////////////////////////////////////////////////////////////
        cuerpo_publ = models.TextField()
        #///////////////////////////////////////////////////////////////////////
        imagen_ayuda = models.ImageField(blank=True)

        def __str__(self):
            return '{}'.format(self.user)

class Quejas_Sugerencias(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    motivo = models.CharField(max_length=20)
    queja = models.TextField()

usuario/forms.py
from django import forms
from administrador.views import *
from .models import Usuario, FichaUsuario, Publicaciones, Quejas_Sugerencias
from django.contrib.auth.forms import UserCreationForm
from django.forms.widgets import Textarea
# from django.urls import reverse_lazy

# from django.contrib.auth.forms import UserCreationFor

#///////////////////////////////////////////////////////////////////////
class NuevoUsuario(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = [
            'nombre_usr',
            'primer_apellido',
            'fecha_nacimiento',
            'lugar_procedencia',
            'correo_usr'
            # 'foto_perfil'
        ]
        labels = {
            'nombre_usr':'Nombre DE USUARIO',
            'primer_apellido': 'Apellidos',
            'fecha_nacimiento':'Fecha de Nacimiento',
            'lugar_procedencia': 'Lugar de procedencia',
            'correo_usr':'Correo'
            # 'foto_perfil' : 'Foto de perfil'
        }
        widgets = {
            'nombre_usr':forms.TextInput(attrs={'class':"input100"}),
            'primer_apellido':forms.TextInput(attrs={'class':"input100"}),
            'fecha_nacimiento':forms.TextInput(attrs={'class':"input100",'type':'date'}),
            'lugar_procedencia': forms.TextInput(attrs={'class':"input100"}),
            'correo_usr':forms.TextInput(attrs={'class':"input100"}),
            }


        # def clean_field(self):
        #     print( self.cleaned_data )
        #     return self.cleaned_data

#///////////////////////////////////////////////////////////////////////


class NuevaFicha(forms.ModelForm):
    class Meta:
        model = FichaUsuario
        fields = [
            'titulo_usr',
            'nivel_elo'
        ]
        labels = {
            'titulo_usr' : 'Titulo',
            'nivel_elo' : 'Nivel de Elo'
        }
        widgets = {
            'titulo_usr' : forms.TextInput(attrs={'class':"input100"}),
            'nivel_elo' : forms.TextInput(attrs={'class':"input100"})
        }
#///////////////////////////////////////////////////////////////////////

class NuevaPublicacion(forms.ModelForm):
    class Meta:
        model = Publicaciones
        fields = [
            'titulo_publ',
            'cuerpo_publ',
            'imagen_ayuda'
        ]
        labels = {
            'titulo_publ' : 'Titulo de publicacion',
            'cuerpo_publ' : 'Contenido'
            # 'imagen_ayuda' : 'Imagen de ejemplo'
        }
        widgets = {
            'titulo_publ' : forms.TextInput(attrs={}),
            'cuerpo_publ' : Textarea(attrs={'cols': 80, 'rows': 10}),
        }

class Nuevaqueja(forms.ModelForm):
        class Meta:
            model = Quejas_Sugerencias
            fields = [
                'motivo',
                'queja'
            ]
            labels = {
                'motivo' : 'Motivo',
                'queja' : 'Queja o Sugerencia'
            }
            widgets = {
                'motivo' : forms.TextInput(attrs={}),
                'queja' : Textarea(attrs={'cols': 80, 'rows': 10})
            }

usuario/views.py
from django.shortcuts import render

# Create your views here.

templates/usuario/ficha_usuario.html
{% extends 'cuenta_usuario/iniciar_cuenta.html' %}
{% load static %}
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">

			    
				<div class="login100-pic js-tilt" data-tilt>
					<img src="{% static 'images/img-01.jpg' %}" alt="IMG">
				</div>
                {% block contenedor %}

				<form class="login100-form validate-form" method="POST" action='' enctype="multipart/form-data">
				    {% csrf_token %}
				    {{ form.image }}

				    <input type=submit value="submit" />
		

                
				</form>
				{% endblock contenedor %}

			</div>
		</div>
	</div>

templates/usuario/informacion_usuario.html
{% extends 'cuenta_usuario/iniciar_cuenta.html' %}
{% load static %}
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">

			    
				<div class="login100-pic js-tilt" data-tilt>
					<img src="{% static 'images/img-01.jpg' %}" alt="IMG">
				</div>
				{% block contenedor %}
				
				<form class="login100-form validate-form" method="POST" action=""  enctype="multipart/form-data">

				    {% csrf_token %}
					{{ form }}
					
					{% block buton_crear %} Guardar {% endblock buton_crear %} 
					
				</form>
				{% endblock contenedor %}
				{% block crear_cuenta %}
				Todo bien {{ request.user }}?
				{% endblock crear_cuenta %}

			</div>
		</div>
	</div>

templates/usuario/perfil_usuario.html
{% extends 'Tienda/index.html' %}
{% load static %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link rel="stylesheet" href="{% static 'user_profile/user_profile.css' %}">

<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>

<body>

    {% block content %}
    <section id="banner">

        <div class="inner">
            {% if Pic_user.foto_perfil %} <img align="left" src="{{ MEDIA_URL }} {{ Pic_user.foto_perfil.url }}" class="fb-image-profile thumbnail" style="width:500px; height:400px" alt="Profile image example"> {% endif %}
        </div>

    </section>

    <section id="one">
        <div class="inner">
            <div class="fb-profile-text">
                {% for myinfo in  Usuario_profile %}
                <h1> {{ myinfo.nombre_usr }}  </h1>
                {% for more_info in FichaUsuario_profile %}
                <p> Nivel de Elo: {{ more_info.nivel_elo }}  </p> 
                <p> Titulo: {{ more_info.titulo_usr }}  </p>
                {% endfor %}
                <p> Fecha de nacimiento:  {{ myinfo.fecha_nacimiento }}</p>
                <p> Lugar de procedencia:  {{ myinfo.lugar_procedencia }} </p>
                {% endfor %}



            </div>
        
            {% for articulo in Publicaciones_profile %}
            <div class="card text-center">
            <div class="card-header">
                Publicado por {{ articulo.user }}
            </div>
            <div class="card-body">
                <h5 class="card-title"> {{ articulo.titulo_publ }} </h5>
                <p class="card-text">{{ articulo.cuerpo_publ }}</p>
                
            </div>
            <div class="card-footer text-muted">
                <a href="{% url "administrador:Ver_publicaciones" articulo.pk %}" class="btn btn-primary">Ver</a>
                <a href="{% url "administrador:Editar_publicaciones" articulo.pk %}" class="btn btn-info">Editar</a>
                <a href="{% url "administrador:Eliminar_publicaciones" articulo.pk %}" class="btn btn-danger">Eliminar</a>
            </div>
            <p></p>
        {% endfor %}
        </div>

    </section>

    {% endblock content %}

</body>

templates/usuario/publicaciones.html
{% extends 'Tienda/index.html' %}
{% block content %}
			<section id="footer">
				<div class="inner">
					<header>
						<h2>Nueva publicacion</h2>
					</header>
                    <form method="POST" action="#">
                        {% csrf_token %}
						{{ form }}
						
						<input type="submit" name="Crear"/>
                        
                    </form>
    
					<div class="copyright">
						Comparte tus ideas {{ request.user }}
					</div>
				</div>
			</section>

{% endblock content %}