Chess/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('administrador.urls')),
    path('captcha/', include('captcha.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

administrador/urls.py
from django.urls import path, include
from . import views
from .views import *
from usuario.models import Usuario
from django.conf.urls import url
# from django.contrib.auth.views import LogoutView
# from django.conf import settings

app_name  = 'administrador'

urlpatterns =[
    #///////////////////////////////////////////////////////////////////////
    path('', views.presentacion , name='presentacion'),
    #///////////////////////////////////////////////////////////////////////
    path('nosotros/', views.nosotros , name='nosotros'),
    #///////////////////////////////////////////////////////////////////////
    path('registro/', views.registro,  name='registro'),
    #///////////////////////////////////////////////////////////////////////
    path('tienda_chess/', views.tienda_chess , name='tienda_chess'), #CAMBIAR
    #///////////////////////////////////////////////////////////////////////
    path('configuraciones/', views.configuraciones, name='configuraciones'),
    #///////////////////////////////////////////////////////////////////////
    path('crear_usuario/', views.CrearUsuario.as_view(), name='CrearUsuario'),
    #///////////////////////////////////////////////////////////////////////
    path('logout_cuenta/', views.logout_cuenta, name='logout_cuenta'),
    #///////////////////////////////////////////////////////////////////////
    path('publicaciones/', views.publicaciones, name='publicaciones'),
    #///////////////////////////////////////////////////////////////////////
    path('0006/<int:pk>', views.Editar_usuario.as_view(), name="Editar_usuario"),
    #///////////////////////////////////////////////////////////////////////
    path('llenar_info/', views.llenar_info, name='llenar_info'),
    #///////////////////////////////////////////////////////////////////////
    path('registro_formularios/', views.registro_formularios, name='registro_formularios'),
    #///////////////////////////////////////////////////////////////////////
    path('Tienda/', views.Tienda, name='Tienda'),
    #///////////////////////////////////////////////////////////////////////
    path('perfil_usuario/', views.perfil_usuario, name='perfil_usuario'),
    #///////////////////////////////////////////////////////////////////////

    #///////////////////////////////////////////////////////////////////////
    path('Ver_publicacion/<int:pk>', views.Ver_publicaciones.as_view(), name="Ver_publicaciones"),
    path('Ver_publicaciones_Comunidad/<int:pk>', views.Ver_publicaciones_Comunidad.as_view(), name="Ver_publicaciones_Comunidad"),
    path('Editar_publicacion<int:pk>', views.Editar_publicaciones.as_view(), name="Editar_publicaciones"),
    path('Eliminar_publicacion<int:pk>', views.Eliminar_publicaciones.as_view(), name="Eliminar_publicaciones"),
    #///////////////////////////////////////////////////////////////////////


]

templates/Inicio/about.html
{% extends 'index.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="zxx">

<head>
  <meta charset="utf-8">
  <title>Kross | Portfolio Template</title>

  <!-- mobile responsive meta -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  
  <!-- ** Plugins Needed for the Project ** -->
  <!-- Bootstrap -->
  <link rel="stylesheet" href="{% static 'plugins/bootstrap/bootstrap.min.css' %}">
  <!-- slick slider -->
  <link rel="stylesheet" href="plugins/slick/slick.css">
  <!-- themefy-icon -->
  <link rel="stylesheet" href="plugins/themify-icons/themify-icons.css">

  <!-- Main Stylesheet -->
  <link href="css/style.css" rel="stylesheet">
  
  <!--Favicon-->
  <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
  <link rel="icon" href="images/favicon.ico" type="image/x-icon">

</head>

<body>

{% block contenedor %}

<!-- Work Process -->
<section class="section">
  <div class="container">
    <div class="row justify-content-around">
      <div class="col-lg-12 text-center">
        <h2 class="section-title">Nuestra Comunidad</h2>
      </div>
      <div class="col-lg-3 col-md-4 text-center hover-shadow pt-3">
        <div class="">
          <h4 class="mb-4">No importa el nivel</h4>
          <p>Ya sea que tengas un gran Elo o nada de nivel, en Don capablanca siempre habra un espacio para ti, 
          somos una comunidad que acepta a todos!!!</p>
        </div>
      </div>
      <div class="col-lg-3 col-md-4 text-center hover-shadow pt-3">
        <h4 class="mb-4">Aprende algo nuevo</h4>
        <p></p>
      </div>
      <div class="col-lg-3 col-md-4 text-center hover-shadow pt-3">
        <h4 class="mb-4">Comparte lo que sabes</h4>
        <p>Uno de los pasos para crecer personalmente, profesionalmente o de la manera que sea, es COMPARTIR tus 
        conocimientos, siempre habra algo nuevo que compartir </p>
      </div>
    </div>
  </div>
</section>
<!-- ./Work Process -->

<!-- team -->
<section class="section bg-cover" data-background="{% static 'images/backgrounds/team-bg.png' %}">
  <div class="container">
    <div class="row">
      <div class="col-12 text-center">
        <h2 class="section-title">Patrocinadores</h2>
      </div>
      <div class="col-md-4 col-sm-6 mb-4 mb-md-0">
        <div class="card text-center">
          <img src="{% static 'images/team/mikelogo.jpg' %}" class="card-img-top">
          <div class="card-body">
            <h4 class="card-title">MACC CODES</h4>
            <p class="text-light font-secondary">Project Manager</p>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-sm-6 mb-4 mb-md-0">
        <div class="card text-center">
          <img src="{% static 'images/team/mikelogo.jpg' %}" class="card-img-top">
          <div class="card-body">
            <h4 class="card-title">MACC CODES</h4>
            <p class="text-light font-secondary">Project Manager</p>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-sm-6 mb-4 mb-md-0">
        <div class="card text-center">
          <img src="{% static 'images/team/mikelogo.jpg' %}" class="card-img-top">
          <div class="card-body">
            <h4 class="card-title">MACC CODES</h4>
            <p class="text-light font-secondary">Project Manager</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- /team -->


{% endblock contenedor %}
<!-- /footer -->

<!-- jQuery -->
<script src="plugins/jQuery/jquery.min.js"></script>
<!-- Bootstrap JS -->
<script src="plugins/bootstrap/bootstrap.min.js"></script>
<!-- slick slider -->
<script src="plugins/slick/slick.min.js"></script>
<!-- filter -->
<script src="plugins/shuffle/shuffle.min.js"></script>

<!-- Main Script -->
<script src="js/script.js"></script>

</body>
</html>

templates/Inicio/index.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>
  <meta charset="utf-8">
  <title>Don capablanca</title>

  <!-- mobile responsive meta -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <!-- ** Plugins Needed for the Project ** -->
  <!-- Bootstrap -->
  <link rel="stylesheet" href="{% static 'plugins/bootstrap/bootstrap.min.css' %}">
  <!-- slick slider -->
  <link rel="stylesheet" href="{% static 'plugins/slick/slick.css' %}">
  <!-- themefy-icon -->
  <link rel="stylesheet" href="{% static 'plugins/themify-icons/themify-icons.css' %}">

  <!-- Main Stylesheet -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">

  <!--Favicon-->
  <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
  <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">

</head>

<body>

{% block header_ajedrez %}
<header class="navigation fixed-top">
  <nav class="navbar navbar-expand-lg navbar-dark">
    <h3>Don Capablanca</h3>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation"
      aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse text-center" id="navigation">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'administrador:presentacion' %}">Menu</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Nosotros</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'administrador:registro' %}">Iniciar sesion</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'administrador:CrearUsuario' %}">Crear sesion</a>
        </li>
      </ul>
    </div>
  </nav>
</header>
{% endblock header_ajedrez %}


<section class="hero-area bg-primary" id="parallax">

  <div class="container">
    <div class="row">
      <div class="layer-bg w-100">
        <img width='100%' src="{% static 'images/header.jpg'%}" alt="bg-shape">
      </div>
    </div>
  </div>

</section>

{% block contenedor %}
<!-- about -->
<section class="section">
  <div class="container">
    <div class="row">
      <div class="col-lg-10 mx-auto text-center">
        <p class="font-secondary paragraph-lg text-dark">
        Don Capablanca es una gran comunidad de ajedrez en la cual podras, compartir tu conocimiento
         con todo el mundo, Todos son bienvenidos, no importa que nivel tengas. Tenemos un lugar para ti!
        </p>
        <a href="#" class="btn btn-transparent">Mas informacion</a>
      </div>
    </div>
  </div>
</section>
<!-- /about -->

<!-- experience -->
<section class="section">
  <div class="container">
    <div class="row justify-content-around">
      <div class="col-lg-12 text-center">
        <h2 class="section-title">Negocio</h2>
      </div>
      <div class="col-lg-3 col-md-4 text-center">
      <h4>Tableros</4>

      </div>
      <div class="col-lg-3 col-md-4 text-center">
        <h4>Piezas</4>
      </div>
      <div class="col-lg-3 col-md-4 text-center">
        <h4>Equipos completos</4>
      </div>
    </div>
  </div>
</section>
<!-- ./experience -->


<!-- services -->
<section class="section">
  <div class="container">
    <div class="row">
      <div class="col-12 text-center">
        <h2 class="section-title">Services</h2>
      </div>
      <div class="col-md-4 mb-4 mb-md-0">
        <div class="card hover-shadow shadow">
          <div class="card-body text-center px-4 py-5">
            <i class="ti-palette icon mb-5 d-inline-block"></i>
            <h4 class="mb-4">Productos</h4>
            <p>Encuentra los mejores productos
            </p>
          </div>
        </div>
      </div>
      <div class="col-md-4 mb-4 mb-md-0">
        <div class="card active-bg-primary hover-shadow shadow">
          <div class="card-body text-center px-4 py-5">
            <i class="ti-vector icon mb-5 d-inline-block"></i>
            <h4 class="mb-4">Diseno Software</h4>
            <p>MACC Software es una empresa desarrolladora comprometida a mejorar la vida de
            las personas por medio de software facil de implementar </p>
          </div>
        </div>
      </div>
      <div class="col-md-4 mb-4 mb-md-0">
        <div class="card hover-shadow shadow">
          <div class="card-body text-center px-4 py-5">
            <i class="ti-panel icon mb-5 d-inline-block"></i>
            <h4 class="mb-4">Comunidad de Ajedrez</h4>
            <p>Nuestra comuidad de ajedrexz siempre esta dispuesta a ayudar a las personas con cualquier tipo de
            problema dentro del ajedrez</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- /services -->


<!-- testimonial -->
<section class="section bg-primary position-relative testimonial-bg-shapes">
  <div class="container">
    <div class="row">
      <div class="col-12 text-center">
        <h2 class="section-title text-white mb-5">Patrocinadores</h2>
      </div>
      <div class="col-lg-10 mx-auto testimonial-slider">
        <!-- slider-item -->
        <div class="text-center testimonial-content">
          <i class="ti-quote-right text-white icon mb-4 d-inline-block"></i>
          <p class="text-white mb-4">MACC CODES</p>
          <img class="img-fluid rounded-circle mb-4 d-inline-block" src="images/testimonial/client-1.png"
            alt="client-image">
          <h4 class="text-white">Miguel Cardona </h4>
          <h6 class="text-light mb-4">mikesservices199@gmail.com</h6>
        </div>
        <!-- slider-item -->
        <div class="text-center testimonial-content">
          <i class="ti-quote-right text-white icon mb-4 d-inline-block"></i>
          <p class="text-white mb-4">MACC CODES</p>
          <img class="img-fluid rounded-circle mb-4 d-inline-block" src="images/testimonial/client-1.png"
            alt="client-image">
          <h4 class="text-white">Miguel Cardona</h4>
          <h6 class="text-light mb-4">mikesservices199@gmail.com</h6>
        </div>
        <!-- slider-item -->
        <div class="text-center testimonial-content">
          <i class="ti-quote-right text-white icon mb-4 d-inline-block"></i>
          <p class="text-white mb-4">MACC CODES</p>
          <img class="img-fluid rounded-circle mb-4 d-inline-block" src="images/testimonial/client-1.png"
            alt="client-image">
          <h4 class="text-white">Miguel Cardona</h4>
          <h6 class="text-light mb-4">mikesservices199@gmail.com</h6>
        </div>
      </div>
    </div>
  </div>
  <!-- bg shapes -->
</section>
<!-- /testimonial -->

{% endblock contenedor %}

{% block footer %}
<!-- footer -->
<footer class="bg-dark footer-section">
  <div class="section">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <h5 class="text-light">Email</h5>
          <p class="text-white paragraph-lg font-secondary">mikesservices199@gmail.com</p>
        </div>
        <div class="col-md-4">
          <h5 class="text-light"> Telefono</h5>
          <p class="text-white paragraph-lg font-secondary">+52 663 125 17 23</p>
        </div>
        <div class="col-md-4">
          <h5 class="text-light">Direcion</h5>
          <p class="text-white paragraph-lg font-secondary"> Altiplano, Baja California, Mexico</p>
        </div>
      </div>
    </div>
  </div>
</footer>
{% endblock footer %}

<!-- /footer -->

<!-- jQuery -->
<script src="{% static 'plugins/jQuery/jquery.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'plugins/bootstrap/bootstrap.min.js' %}"></script>
<!-- slick slider -->
<script src="{% static 'plugins/slick/slick.min.js' %}"></script>
<!-- filter -->
<script src="{% static 'plugins/shuffle/shuffle.min.js' %}"></script>

<!-- Main Script -->
<script src="{% static 'js/script.js' %}"></script>

</body>
</html>

templates/Inicio/presentacion.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="{% static 'csss/presentacion.css' %}" />
        <title>Don Capablanca</title>
    </head>
    <body>
        <header>Este es mi header</header>
        <h1>Hola a todos!</h1>
    </body>
</html>