Chess/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('administrador.urls')),
    path('captcha/', include('captcha.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

administrador/urls.py
from django.urls import path, include
from . import views
from .views import *
from usuario.models import Usuario
from django.conf.urls import url
# from django.contrib.auth.views import LogoutView
# from django.conf import settings

app_name  = 'administrador'

urlpatterns =[
    #///////////////////////////////////////////////////////////////////////
    path('', views.presentacion , name='presentacion'),
    #///////////////////////////////////////////////////////////////////////
    path('nosotros/', views.nosotros , name='nosotros'),
    #///////////////////////////////////////////////////////////////////////
    path('registro/', views.registro,  name='registro'),
    #///////////////////////////////////////////////////////////////////////
    path('tienda_chess/', views.tienda_chess , name='tienda_chess'), #CAMBIAR
    #///////////////////////////////////////////////////////////////////////
    path('configuraciones/', views.configuraciones, name='configuraciones'),
    #///////////////////////////////////////////////////////////////////////
    path('crear_usuario/', views.CrearUsuario.as_view(), name='CrearUsuario'),
    #///////////////////////////////////////////////////////////////////////
    path('logout_cuenta/', views.logout_cuenta, name='logout_cuenta'),
    #///////////////////////////////////////////////////////////////////////
    path('publicaciones/', views.publicaciones, name='publicaciones'),
    #///////////////////////////////////////////////////////////////////////
    path('0006/<int:pk>', views.Editar_usuario.as_view(), name="Editar_usuario"),
    #///////////////////////////////////////////////////////////////////////
    path('llenar_info/', views.llenar_info, name='llenar_info'),
    #///////////////////////////////////////////////////////////////////////
    path('registro_formularios/', views.registro_formularios, name='registro_formularios'),
    #///////////////////////////////////////////////////////////////////////
    path('Tienda/', views.Tienda, name='Tienda'),
    #///////////////////////////////////////////////////////////////////////
    path('perfil_usuario/', views.perfil_usuario, name='perfil_usuario'),
    #///////////////////////////////////////////////////////////////////////

    #///////////////////////////////////////////////////////////////////////
    path('Ver_publicacion/<int:pk>', views.Ver_publicaciones.as_view(), name="Ver_publicaciones"),
    path('Ver_publicaciones_Comunidad/<int:pk>', views.Ver_publicaciones_Comunidad.as_view(), name="Ver_publicaciones_Comunidad"),
    path('Editar_publicacion<int:pk>', views.Editar_publicaciones.as_view(), name="Editar_publicaciones"),
    path('Eliminar_publicacion<int:pk>', views.Eliminar_publicaciones.as_view(), name="Eliminar_publicaciones"),
    #///////////////////////////////////////////////////////////////////////


]

templates/Tienda/index.html
{% load static %}
<!DOCTYPE HTML>
<!--
	Introspect by TEMPLATED
	templated.co @templatedco
	Released for free under the Creative Commons Attribution 3.0 license (templated.co/license)
-->
<html>
	<head>
		<!-- CSS only  SE TIENE QUE IMPORTAR BOOTSTRAP-->
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
		<title>Don capablanca</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'css_interface/assets/css/main.css' %}" />
	</head>

	<body>

		<!-- Header -->
		{% block header %}
			<header id="header">

				<div class="inner">
				    <a href="{% url 'administrador:tienda_chess' %}" class="logo">Bienvenid@ {{ request.user }}</a>
					<!--<nav id="nav">-->
    					<a href="{% url 'administrador:perfil_usuario' %}">Mi cuenta</a>
    					<a href="{% url 'administrador:publicaciones' %}">Crear</a>
    					<a href="{% url 'administrador:Tienda' %}">Tienda</a>
    					{% for mike in info_usuarios %}
    					<a href="{% url 'administrador:Editar_usuario' mike.pk %}">Configuraciones</a>
    					{% endfor %}

    					<a href="{% url 'administrador:logout_cuenta' %}">Salir</a>
					<!--</nav>-->
				</div>
			</header>
			<!--<span class="fa fa-bars"></span>-->
		{% endblock header %}


        {% block content %}
		<!-- Banner -->
			<section id="banner">
				<div class="inner">
					<h1>Un lugar <span>hecho para ti {{ request.user }}<br />
				</div>
			</section>

		<!-- One -->
			<section id="one"> <!--Lista de todos los productos que hay -->
				<div class="inner">

				    {% for articulo in publicaciones_usuarios %}
						<div class="card text-center">
						<div class="card-header">
							Publicado por: {{ articulo.user }}
						</div>
						<div class="card-body">
							<h5 class="card-title"> {{ articulo.titulo_publ }} </h5>
							<p class="card-text">{{ articulo.cuerpo_publ }}</p>

						</div>
						<div class="card-footer text-muted">
							<a href="{% url 'administrador:Ver_publicaciones_Comunidad' articulo.pk %}" class="btn btn-primary">Ver publicacion</a>
						</div>
						<p></p>
					{% endfor %}
				</div>
			</section>

		<!-- Footer -->
		    {% block quejas %}
			<section id="footer">
				<div class="inner">
					<header>
						<h2>Quejas o Sugerencias</h2>
					</header>
					<form method="post" action="#">
					    {% csrf_token %}
						{{ form }}
						<li><input type="submit" value="Send Message" class="alt" /></li>

					</form>
					<div class="copyright">
						&copy; Untitled Design: <a href="https://templated.co/">TEMPLATED</a>. Images <a href="https://unsplash.com/">Unsplash</a>
					</div>
				</div>
			</section>
		    {% endblock quejas %}

		{% endblock content %}

		<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/skel.min.js"></script>
			<script src="assets/js/util.js"></script>
			<script src="assets/js/main.js"></script>

	</body>
</html>

templates/Tienda/tienda.html
{% extends 'Tienda/index.html' %}

{% block content %}
<!-- One -->
<section id="one"> <!--Lista de todos los productos que hay -->
    <div class="inner">

        <!-- FILTROS DE BUSQUEDA -->
        <form method="get">
            {{ busqueda_productos.form }}
            <input type="submit" />
        </form>

        {% for obj in busqueda_productos.qs %}
            <div class="card text-center">
            <div class="card-header">
                {{ obj.tipo_producto }}
            </div>
            <div class="card-body">
                <h5 class="card-title">Special title treatment</h5>
                <img src="{{ MEDIA_URL }} {{ obj.imagen_producto.url }}" style="width:300px; height:300px"/>
                <p class="card-text">{{ obj.descipcion_producto }}</p>

            </div>
            <div class="card-footer text-muted">
                <a href="#" class="btn btn-primary">Ordenar</a>
            </div>
            <p></p>
        {% endfor %}
    </div>
</section>
{% endblock content %}

templates/Tienda/ver_publicaciones.html
{% extends 'Tienda/index.html' %}
<body>
    {% block content %}
                <div class="card text-center">
                    <div class="card-header">
                        Publicado por {{ object.user }}
                    </div>
                    <div class="card-body">
                        <h5 class="card-title"> {{ object.titulo_publ }} </h5>
                        <p class="card-text">{{ object.cuerpo_publ }}</p>
                        
                    </div>
                    <div class="card-footer text-muted">
                        <a class="btn btn-primary" href="{% url 'administrador:tienda_chess' %}"> Volver </a>
                    </div>
                    
                </div>
    {% endblock content %}

</body>